GET http://localhost:5000/customer

###
GET http://localhost:5000/customer/5ec3cafe6a944408985d7c25

###

POST http://localhost:5000/customer/register
Content-Type: application/json

{
"username": "Fippe5",
"password": "12345",
"firstName": "Fredrik",
"lastName": "Thelin",
"street": "Älvornas Väg 2",
"city": "Älvängen",
"zip": "44634",
"phone": "0734340604",
"email": "fredrikthelin82@gmail.com"
}

###

POST http://localhost:5000/customer/login
Content-Type: application/json

{
"username": "Fippe3",
"password": "12345"
}

###

POST http://localhost:5000/customer/logout

###