GET http://localhost:5000/customer

###
GET http://localhost:5000/customer/5ed62796602ca6254c8aa5df

###


//Klient skickar "customer" eller "wantsToBeAdmin" som role.
//Klienten kan sen lista alla "WantsToBeAdmin" och en Admin kan ändra roll. 
POST http://localhost:5000/customer/register
Content-Type: application/json

{
"password": "12345",
"firstName": "Kalle",
"lastName": "Thelin",
"street": "Älvornas Väg 2",
"city": "Älvängen",
"zip": "44634",
"country": "Sverige",
"phone": "0734340604",
"email": "fredrikthelind82@gmail.com",
"role": "admin"
}


###

POST http://localhost:5000/customer/login
Content-Type: application/json

{
"email": "fredrikthelin82@gmail.com",
"password": "123456"
}

###

POST http://localhost:5000/customer/logout

###


PUT http://localhost:5000/customer/5ed79dd283e7bf4b88c60805
Content-Type: application/json

{  
  "role": "admin"
}

###