GET http://localhost:5000/customer

###
GET http://localhost:5000/customer/5ecb84c77fe48c1ecc19c70b

###


//Klient skickar "customer" eller "wantsToBeAdmin" som role.
//Klienten kan sen lista alla "WantsToBeAdmin" och en Admin kan ändra roll. 
POST http://localhost:5000/customer/register
Content-Type: application/json

{
"username": "Fippe",
"password": "12345",
"firstName": "Fredrik",
"lastName": "Thelin",
"street": "Älvornas Väg 2",
"city": "Älvängen",
"zip": "44634",
"phone": "0734340604",
"email": "fredrikthelin82@gmail.com",
"role": "admin"
}


###

POST http://localhost:5000/customer/login
Content-Type: application/json

{
"username": "FredrikAdmin",
"password": "12345"
}

###

POST http://localhost:5000/customer/logout

###