GET http://localhost:5000/product/

###

GET http://localhost:5000/product/5ecbc325f1c6f52fe81cd477

###


POST http://localhost:5000/product
Content-Type: application/json

{
  "category": ["pattern"],
  "quantity": 10,
  "url": "https://az666937.vo.msecnd.net/64/df80d819-f84e-4619-bfd1-1ba4e6bfad48?w=740&h=740&mode=crop&scale=both",
  "price": 999,
  "description": "Familj II är en tapetkollektion för hela familjen, både drömmaren och den som gillar struktur. Härliga färger, lekfullt och grafiskt, för det moderna skandinaviska hemmet.",
  "brand": "AVA DARK BLUE",
  "designer": "Sandberg",
  "ref": "AVA.D.B",
  "dimensions": "60cm x 270cm"
}

###

PUT http://localhost:5000/product/5ecbc325f1c6f52fe81cd477
Content-Type: application/json

{
  "category": "pattern",
  "quantity": 60,
  "url": "https://az666937.vo.msecnd.net/64/df80d819-f84e-4619-bfd1-1ba4e6bfad48?w=740&h=740&mode=crop&scale=both",
  "price": 999,
  "description": "Familj II är en tapetkollektion för hela familjen, både drömmaren och den som gillar struktur. Härliga färger, lekfullt och grafiskt, för det moderna skandinaviska hemmet.",
  "brand": "AVA DARK BLUE",
  "designer": "Sandberg. F",
  "ref": "AVA.D.B",
  "dimensions": "60cm x 270cm"
}

###

DELETE http://localhost:5000/product/5ecbc325f1c6f52fe81cd477

###