POST http://localhost:5000/upload
Content-Type: multipart/form-data; boundary=FormDataRow

--FormDataRow
Content-Disposition: form-data; name="image"; filename="earth.jpg"
Content-Type: image/jpeg

< ./earth.jpg
--FormDataRow--
### Tänk på följande:
### ALLA boundary's måste BÖRJA med --
### SISTA boundary'n måste AVSLUTAS med --

GET http://localhost:5000/upload/5ed012ffa0ff213e941222fc